<?php

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Uncomment the below to wipe the table clean before populating
        DB::table('currencies')->truncate();
        $currencies = [
            [
                'priority' => '100',
                'iso_code' => 'AED',
                'currency' => 'AED',
                'name' => 'United Arab Emirates Dirham',
                'symbol' => 'د.إ',
                'subunit' => 'Fils',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '784',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'AFN',
                'currency' => 'AFN',
                'name' => 'Afghan Afghani',
                'symbol' => '؋',
                'subunit' => 'Pul',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '971',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ALL',
                'currency' => 'ALL',
                'name' => 'Albanian Lek',
                'symbol' => 'L',
                'subunit' => 'Qintar',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '008',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'AMD',
                'currency' => 'AMD',
                'name' => 'Armenian Dram',
                'symbol' => 'դր.',
                'subunit' => 'Luma',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '051',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ANG',
                'currency' => 'ANG',
                'name' => 'Netherlands Antillean Gulden',
                'symbol' => 'ƒ',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x0192;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '532',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'AOA',
                'currency' => 'AOA',
                'name' => 'Angolan Kwanza',
                'symbol' => 'Kz',
                'subunit' => 'Cêntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '973',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ARS',
                'currency' => 'ARS',
                'name' => 'Argentine Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '032',
                'currency_rate' => 1
            ],
            [
                'priority' => '4',
                'iso_code' => 'AUD',
                'currency' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '036',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'AWG',
                'currency' => 'AWG',
                'name' => 'Aruban Florin',
                'symbol' => 'ƒ',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x0192;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '533',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'AZN',
                'currency' => 'AZN',
                'name' => 'Azerbaijani Manat',
                'symbol' => 'null',
                'subunit' => 'Qəpik',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '944',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BAM',
                'currency' => 'BAM',
                'name' => 'Bosnia and Herzegovina Convertible Mark',
                'symbol' => 'КМ',
                'subunit' => 'Fening',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '977',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BBD',
                'currency' => 'BBD',
                'name' => 'Barbadian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '052',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BDT',
                'currency' => 'BDT',
                'name' => 'Bangladeshi Taka',
                'symbol' => '৳',
                'subunit' => 'Paisa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '050',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BGN',
                'currency' => 'BGN',
                'name' => 'Bulgarian Lev',
                'symbol' => 'лв',
                'subunit' => 'Stotinka',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '975',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BHD',
                'currency' => 'BHD',
                'name' => 'Bahraini Dinar',
                'symbol' => 'ب.د',
                'subunit' => 'Fils',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '048',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BIF',
                'currency' => 'BIF',
                'name' => 'Burundian Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '108',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BMD',
                'currency' => 'BMD',
                'name' => 'Bermudian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '060',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BND',
                'currency' => 'BND',
                'name' => 'Brunei Dollar',
                'symbol' => '$',
                'subunit' => 'Sen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '096',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BOB',
                'currency' => 'BOB',
                'name' => 'Bolivian Boliviano',
                'symbol' => 'Bs.',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '068',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BRL',
                'currency' => 'BRL',
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => 'R$',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '986',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BSD',
                'currency' => 'BSD',
                'name' => 'Bahamian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '044',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BTN',
                'currency' => 'BTN',
                'name' => 'Bhutanese Ngultrum',
                'symbol' => 'Nu.',
                'subunit' => 'Chertrum',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '064',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BWP',
                'currency' => 'BWP',
                'name' => 'Botswana Pula',
                'symbol' => 'P',
                'subunit' => 'Thebe',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '072',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BYR',
                'currency' => 'BYR',
                'name' => 'Belarusian Ruble',
                'symbol' => 'Br',
                'subunit' => 'Kapyeyka',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '974',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'BZD',
                'currency' => 'BZD',
                'name' => 'Belize Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '084',
                'currency_rate' => 1
            ],
            [
                'priority' => '5',
                'iso_code' => 'CAD',
                'currency' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '124',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CDF',
                'currency' => 'CDF',
                'name' => 'Congolese Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '976',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CHF',
                'currency' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'Fr',
                'subunit' => 'Rappen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '756',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CLF',
                'currency' => 'CLF',
                'name' => 'Unidad de Fomento',
                'symbol' => 'UF',
                'subunit' => 'Peso',
                'subunit_to_unit' => '1',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '990',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CLP',
                'currency' => 'CLP',
                'name' => 'Chilean Peso',
                'symbol' => '$',
                'subunit' => 'Peso',
                'subunit_to_unit' => '1',
                'symbol_first' => 'true',
                'html_entity' => '&#36;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '152',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CNY',
                'currency' => 'CNY',
                'name' => 'Chinese Renminbi Yuan',
                'symbol' => '¥',
                'subunit' => 'Fen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#20803;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '156',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'COP',
                'currency' => 'COP',
                'name' => 'Colombian Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '170',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CRC',
                'currency' => 'CRC',
                'name' => 'Costa Rican Colón',
                'symbol' => '₡',
                'subunit' => 'Céntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A1;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '188',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CUC',
                'currency' => 'CUC',
                'name' => 'Cuban Convertible Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '931',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CUP',
                'currency' => 'CUP',
                'name' => 'Cuban Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '192',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CVE',
                'currency' => 'CVE',
                'name' => 'Cape Verdean Escudo',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '132',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'CZK',
                'currency' => 'CZK',
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'subunit' => 'Haléř',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '203',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'DJF',
                'currency' => 'DJF',
                'name' => 'Djiboutian Franc',
                'symbol' => 'Fdj',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '262',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'DKK',
                'currency' => 'DKK',
                'name' => 'Danish Krone',
                'symbol' => 'kr',
                'subunit' => 'Øre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '208',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'DOP',
                'currency' => 'DOP',
                'name' => 'Dominican Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '214',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'DZD',
                'currency' => 'DZD',
                'name' => 'Algerian Dinar',
                'symbol' => 'د.ج',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '012',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'EGP',
                'currency' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => 'ج.م',
                'subunit' => 'Piastre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '818',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ERN',
                'currency' => 'ERN',
                'name' => 'Eritrean Nakfa',
                'symbol' => 'Nfk',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '232',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ETB',
                'currency' => 'ETB',
                'name' => 'Ethiopian Birr',
                'symbol' => 'Br',
                'subunit' => 'Santim',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '230',
                'currency_rate' => 1
            ],
            [
                'priority' => '2',
                'iso_code' => 'EUR',
                'currency' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20AC;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '978',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'FJD',
                'currency' => 'FJD',
                'name' => 'Fijian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '242',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'FKP',
                'currency' => 'FKP',
                'name' => 'Falkland Pound',
                'symbol' => '£',
                'subunit' => 'Penny',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '238',
                'currency_rate' => 1
            ],
            [
                'priority' => '3',
                'iso_code' => 'GBP',
                'currency' => 'GBP',
                'name' => 'British Pound',
                'symbol' => '£',
                'subunit' => 'Penny',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '826',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GEL',
                'currency' => 'GEL',
                'name' => 'Georgian Lari',
                'symbol' => 'ლ',
                'subunit' => 'Tetri',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '981',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GHS',
                'currency' => 'GHS',
                'name' => 'Ghanaian Cedi',
                'symbol' => '₵',
                'subunit' => 'Pesewa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B5;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '936',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GIP',
                'currency' => 'GIP',
                'name' => 'Gibraltar Pound',
                'symbol' => '£',
                'subunit' => 'Penny',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '292',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GMD',
                'currency' => 'GMD',
                'name' => 'Gambian Dalasi',
                'symbol' => 'D',
                'subunit' => 'Butut',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '270',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GNF',
                'currency' => 'GNF',
                'name' => 'Guinean Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '324',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GTQ',
                'currency' => 'GTQ',
                'name' => 'Guatemalan Quetzal',
                'symbol' => 'Q',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '320',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'GYD',
                'currency' => 'GYD',
                'name' => 'Guyanese Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '328',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'HKD',
                'currency' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '344',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'HNL',
                'currency' => 'HNL',
                'name' => 'Honduran Lempira',
                'symbol' => 'L',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '340',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'HRK',
                'currency' => 'HRK',
                'name' => 'Croatian Kuna',
                'symbol' => 'kn',
                'subunit' => 'Lipa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '191',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'HTG',
                'currency' => 'HTG',
                'name' => 'Haitian Gourde',
                'symbol' => 'G',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '332',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'HUF',
                'currency' => 'HUF',
                'name' => 'Hungarian Forint',
                'symbol' => 'Ft',
                'subunit' => 'Fillér',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '348',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'IDR',
                'currency' => 'IDR',
                'name' => 'Indonesian Rupiah',
                'symbol' => 'Rp',
                'subunit' => 'Sen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '360',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ILS',
                'currency' => 'ILS',
                'name' => 'Israeli New Sheqel',
                'symbol' => '₪',
                'subunit' => 'Agora',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20AA;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '376',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'INR',
                'currency' => 'INR',
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'subunit' => 'Paisa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20b9;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '356',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'IQD',
                'currency' => 'IQD',
                'name' => 'Iraqi Dinar',
                'symbol' => 'ع.د',
                'subunit' => 'Fils',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '368',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'IRR',
                'currency' => 'IRR',
                'name' => 'Iranian Rial',
                'symbol' => '﷼',
                'subunit' => 'Dinar',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#xFDFC;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '364',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ISK',
                'currency' => 'ISK',
                'name' => 'Icelandic Króna',
                'symbol' => 'kr',
                'subunit' => 'Eyrir',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '352',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'JMD',
                'currency' => 'JMD',
                'name' => 'Jamaican Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '388',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'JOD',
                'currency' => 'JOD',
                'name' => 'Jordanian Dinar',
                'symbol' => 'د.ا',
                'subunit' => 'Piastre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '400',
                'currency_rate' => 1
            ],
            [
                'priority' => '6',
                'iso_code' => 'JPY',
                'currency' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'subunit' => 'null',
                'subunit_to_unit' => '1',
                'symbol_first' => 'true',
                'html_entity' => '&#x00A5;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '392',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KES',
                'currency' => 'KES',
                'name' => 'Kenyan Shilling',
                'symbol' => 'KSh',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '404',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KGS',
                'currency' => 'KGS',
                'name' => 'Kyrgyzstani Som',
                'symbol' => 'som',
                'subunit' => 'Tyiyn',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '417',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KHR',
                'currency' => 'KHR',
                'name' => 'Cambodian Riel',
                'symbol' => '៛',
                'subunit' => 'Sen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x17DB;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '116',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KMF',
                'currency' => 'KMF',
                'name' => 'Comorian Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '174',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KPW',
                'currency' => 'KPW',
                'name' => 'North Korean Won',
                'symbol' => '₩',
                'subunit' => 'Chŏn',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20A9;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '408',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KRW',
                'currency' => 'KRW',
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'subunit' => 'null',
                'subunit_to_unit' => '1',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A9;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '410',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KWD',
                'currency' => 'KWD',
                'name' => 'Kuwaiti Dinar',
                'symbol' => 'د.ك',
                'subunit' => 'Fils',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '414',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KYD',
                'currency' => 'KYD',
                'name' => 'Cayman Islands Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '136',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'KZT',
                'currency' => 'KZT',
                'name' => 'Kazakhstani Tenge',
                'symbol' => '〒',
                'subunit' => 'Tiyn',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '398',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LAK',
                'currency' => 'LAK',
                'name' => 'Lao Kip',
                'symbol' => '₭',
                'subunit' => 'Att',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20AD;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '418',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LBP',
                'currency' => 'LBP',
                'name' => 'Lebanese Pound',
                'symbol' => 'ل.ل',
                'subunit' => 'Piastre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '422',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LKR',
                'currency' => 'LKR',
                'name' => 'Sri Lankan Rupee',
                'symbol' => '₨',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x0BF9;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '144',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LRD',
                'currency' => 'LRD',
                'name' => 'Liberian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '430',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LSL',
                'currency' => 'LSL',
                'name' => 'Lesotho Loti',
                'symbol' => 'L',
                'subunit' => 'Sente',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '426',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LTL',
                'currency' => 'LTL',
                'name' => 'Lithuanian Litas',
                'symbol' => 'Lt',
                'subunit' => 'Centas',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '440',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LVL',
                'currency' => 'LVL',
                'name' => 'Latvian Lats',
                'symbol' => 'Ls',
                'subunit' => 'Santīms',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '428',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'LYD',
                'currency' => 'LYD',
                'name' => 'Libyan Dinar',
                'symbol' => 'ل.د',
                'subunit' => 'Dirham',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '434',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MAD',
                'currency' => 'MAD',
                'name' => 'Moroccan Dirham',
                'symbol' => 'د.م.',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '504',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MDL',
                'currency' => 'MDL',
                'name' => 'Moldovan Leu',
                'symbol' => 'L',
                'subunit' => 'Ban',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '498',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MGA',
                'currency' => 'MGA',
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'subunit' => 'Iraimbilanja',
                'subunit_to_unit' => '5',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '969',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MKD',
                'currency' => 'MKD',
                'name' => 'Macedonian Denar',
                'symbol' => 'ден',
                'subunit' => 'Deni',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '807',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MMK',
                'currency' => 'MMK',
                'name' => 'Myanmar Kyat',
                'symbol' => 'K',
                'subunit' => 'Pya',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '104',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MNT',
                'currency' => 'MNT',
                'name' => 'Mongolian Tögrög',
                'symbol' => '₮',
                'subunit' => 'Möngö',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20AE;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '496',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MOP',
                'currency' => 'MOP',
                'name' => 'Macanese Pataca',
                'symbol' => 'P',
                'subunit' => 'Avo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '446',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MRO',
                'currency' => 'MRO',
                'name' => 'Mauritanian Ouguiya',
                'symbol' => 'UM',
                'subunit' => 'Khoums',
                'subunit_to_unit' => '5',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '478',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MUR',
                'currency' => 'MUR',
                'name' => 'Mauritian Rupee',
                'symbol' => '₨',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A8;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '480',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MVR',
                'currency' => 'MVR',
                'name' => 'Maldivian Rufiyaa',
                'symbol' => 'MVR',
                'subunit' => 'Laari',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '462',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MWK',
                'currency' => 'MWK',
                'name' => 'Malawian Kwacha',
                'symbol' => 'MK',
                'subunit' => 'Tambala',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '454',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MXN',
                'currency' => 'MXN',
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '484',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MYR',
                'currency' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'subunit' => 'Sen',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '458',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'MZN',
                'currency' => 'MZN',
                'name' => 'Mozambican Metical',
                'symbol' => 'MTn',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '943',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NAD',
                'currency' => 'NAD',
                'name' => 'Namibian Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '516',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NGN',
                'currency' => 'NGN',
                'name' => 'Nigerian Naira',
                'symbol' => '₦',
                'subunit' => 'Kobo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20A6;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '566',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NIO',
                'currency' => 'NIO',
                'name' => 'Nicaraguan Córdoba',
                'symbol' => 'C$',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '558',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NOK',
                'currency' => 'NOK',
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'subunit' => 'Øre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => 'kr',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '578',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NPR',
                'currency' => 'NPR',
                'name' => 'Nepalese Rupee',
                'symbol' => '₨',
                'subunit' => 'Paisa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A8;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '524',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'NZD',
                'currency' => 'NZD',
                'name' => 'New Zealand Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '554',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'OMR',
                'currency' => 'OMR',
                'name' => 'Omani Rial',
                'symbol' => 'ر.ع.',
                'subunit' => 'Baisa',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'true',
                'html_entity' => '&#xFDFC;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '512',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PAB',
                'currency' => 'PAB',
                'name' => 'Panamanian Balboa',
                'symbol' => 'B/.',
                'subunit' => 'Centésimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '590',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PEN',
                'currency' => 'PEN',
                'name' => 'Peruvian Nuevo Sol',
                'symbol' => 'S/.',
                'subunit' => 'Céntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => 'S/.',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '604',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PGK',
                'currency' => 'PGK',
                'name' => 'Papua New Guinean Kina',
                'symbol' => 'K',
                'subunit' => 'Toea',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '598',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PHP',
                'currency' => 'PHP',
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '608',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PKR',
                'currency' => 'PKR',
                'name' => 'Pakistani Rupee',
                'symbol' => '₨',
                'subunit' => 'Paisa',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A8;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '586',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PLN',
                'currency' => 'PLN',
                'name' => 'Polish Złoty',
                'symbol' => 'zł',
                'subunit' => 'Grosz',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => 'z&#322;',
                'decimal_mark' => ',',
                'thousands_separator' => '',
                'iso_numeric' => '985',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'PYG',
                'currency' => 'PYG',
                'name' => 'Paraguayan Guaraní',
                'symbol' => '₲',
                'subunit' => 'Céntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B2;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '600',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'QAR',
                'currency' => 'QAR',
                'name' => 'Qatari Riyal',
                'symbol' => 'ر.ق',
                'subunit' => 'Dirham',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#xFDFC;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '634',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'RON',
                'currency' => 'RON',
                'name' => 'Romanian Leu',
                'symbol' => 'Lei',
                'subunit' => 'Bani',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '946',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'RSD',
                'currency' => 'RSD',
                'name' => 'Serbian Dinar',
                'symbol' => 'РСД',
                'subunit' => 'Para',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '941',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'RUB',
                'currency' => 'RUB',
                'name' => 'Russian Ruble',
                'symbol' => 'р.',
                'subunit' => 'Kopek',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x0440;&#x0443;&#x0431;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '643',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'RWF',
                'currency' => 'RWF',
                'name' => 'Rwandan Franc',
                'symbol' => 'FRw',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '646',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SAR',
                'currency' => 'SAR',
                'name' => 'Saudi Riyal',
                'symbol' => 'ر.س',
                'subunit' => 'Hallallah',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#xFDFC;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '682',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SBD',
                'currency' => 'SBD',
                'name' => 'Solomon Islands Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '090',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SCR',
                'currency' => 'SCR',
                'name' => 'Seychellois Rupee',
                'symbol' => '₨',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20A8;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '690',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SDG',
                'currency' => 'SDG',
                'name' => 'Sudanese Pound',
                'symbol' => '£',
                'subunit' => 'Piastre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '938',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SEK',
                'currency' => 'SEK',
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'subunit' => 'Öre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '',
                'iso_numeric' => '752',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SGD',
                'currency' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '702',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SHP',
                'currency' => 'SHP',
                'name' => 'Saint Helenian Pound',
                'symbol' => '£',
                'subunit' => 'Penny',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '654',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SKK',
                'currency' => 'SKK',
                'name' => 'Slovak Koruna',
                'symbol' => 'Sk',
                'subunit' => 'Halier',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '703',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SLL',
                'currency' => 'SLL',
                'name' => 'Sierra Leonean Leone',
                'symbol' => 'Le',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '694',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SOS',
                'currency' => 'SOS',
                'name' => 'Somali Shilling',
                'symbol' => 'Sh',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '706',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SRD',
                'currency' => 'SRD',
                'name' => 'Surinamese Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '968',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SSP',
                'currency' => 'SSP',
                'name' => 'South Sudanese Pound',
                'symbol' => '£',
                'subunit' => 'piaster',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '728',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'STD',
                'currency' => 'STD',
                'name' => 'São Tomé and Príncipe Dobra',
                'symbol' => 'Db',
                'subunit' => 'Cêntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '678',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SVC',
                'currency' => 'SVC',
                'name' => 'Salvadoran Colón',
                'symbol' => '₡',
                'subunit' => 'Centavo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20A1;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '222',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SYP',
                'currency' => 'SYP',
                'name' => 'Syrian Pound',
                'symbol' => '£S',
                'subunit' => 'Piastre',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x00A3;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '760',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'SZL',
                'currency' => 'SZL',
                'name' => 'Swazi Lilangeni',
                'symbol' => 'L',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '748',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'THB',
                'currency' => 'THB',
                'name' => 'Thai Baht',
                'symbol' => '฿',
                'subunit' => 'Satang',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x0E3F;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '764',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TJS',
                'currency' => 'TJS',
                'name' => 'Tajikistani Somoni',
                'symbol' => 'ЅМ',
                'subunit' => 'Diram',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '972',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TMT',
                'currency' => 'TMT',
                'name' => 'Turkmenistani Manat',
                'symbol' => 'T',
                'subunit' => 'Tenge',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '934',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TND',
                'currency' => 'TND',
                'name' => 'Tunisian Dinar',
                'symbol' => 'د.ت',
                'subunit' => 'Millime',
                'subunit_to_unit' => '1000',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '788',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TOP',
                'currency' => 'TOP',
                'name' => 'Tongan Paʻanga',
                'symbol' => 'T$',
                'subunit' => 'Seniti',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '776',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TRY',
                'currency' => 'TRY',
                'name' => 'Turkish Lira',
                'symbol' => 'TL',
                'subunit' => 'kuruş',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '949',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TTD',
                'currency' => 'TTD',
                'name' => 'Trinidad and Tobago Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '780',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TWD',
                'currency' => 'TWD',
                'name' => 'New Taiwan Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '901',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'TZS',
                'currency' => 'TZS',
                'name' => 'Tanzanian Shilling',
                'symbol' => 'Sh',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '834',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'UAH',
                'currency' => 'UAH',
                'name' => 'Ukrainian Hryvnia',
                'symbol' => '₴',
                'subunit' => 'Kopiyka',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#x20B4;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '980',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'UGX',
                'currency' => 'UGX',
                'name' => 'Ugandan Shilling',
                'symbol' => 'USh',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '800',
                'currency_rate' => 1
            ],
            [
                'priority' => '1',
                'iso_code' => 'USD',
                'currency' => 'USD',
                'name' => 'United States Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '840',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'UYU',
                'currency' => 'UYU',
                'name' => 'Uruguayan Peso',
                'symbol' => '$',
                'subunit' => 'Centésimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x20B1;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '858',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'UZS',
                'currency' => 'UZS',
                'name' => 'Uzbekistani Som',
                'symbol' => 'null',
                'subunit' => 'Tiyin',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '860',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'VEF',
                'currency' => 'VEF',
                'name' => 'Venezuelan Bolívar',
                'symbol' => 'Bs F',
                'subunit' => 'Céntimo',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '937',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'VND',
                'currency' => 'VND',
                'name' => 'Vietnamese Đồng',
                'symbol' => '₫',
                'subunit' => 'Hào',
                'subunit_to_unit' => '10',
                'symbol_first' => 'true',
                'html_entity' => '&#x20AB;',
                'decimal_mark' => ',',
                'thousands_separator' => '.',
                'iso_numeric' => '704',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'VUV',
                'currency' => 'VUV',
                'name' => 'Vanuatu Vatu',
                'symbol' => 'Vt',
                'subunit' => 'null',
                'subunit_to_unit' => '1',
                'symbol_first' => 'true',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '548',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'WST',
                'currency' => 'WST',
                'name' => 'Samoan Tala',
                'symbol' => 'T',
                'subunit' => 'Sene',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '882',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XAF',
                'currency' => 'XAF',
                'name' => 'Central African Cfa Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '950',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XAG',
                'currency' => 'XAG',
                'name' => 'Silver (Troy Ounce)',
                'symbol' => 'oz t',
                'subunit' => 'oz',
                'subunit_to_unit' => '1',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '961',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XAU',
                'currency' => 'XAU',
                'name' => 'Gold (Troy Ounce)',
                'symbol' => 'oz t',
                'subunit' => 'oz',
                'subunit_to_unit' => '1',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '959',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XCD',
                'currency' => 'XCD',
                'name' => 'East Caribbean Dollar',
                'symbol' => '$',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '951',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XDR',
                'currency' => 'XDR',
                'name' => 'Special Drawing Rights',
                'symbol' => 'SDR',
                'subunit' => '',
                'subunit_to_unit' => '1',
                'symbol_first' => 'false',
                'html_entity' => '$',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '960',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XOF',
                'currency' => 'XOF',
                'name' => 'West African Cfa Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '952',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'XPF',
                'currency' => 'XPF',
                'name' => 'Cfp Franc',
                'symbol' => 'Fr',
                'subunit' => 'Centime',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '953',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'YER',
                'currency' => 'YER',
                'name' => 'Yemeni Rial',
                'symbol' => '﷼',
                'subunit' => 'Fils',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '&#xFDFC;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '886',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ZAR',
                'currency' => 'ZAR',
                'name' => 'South African Rand',
                'symbol' => 'R',
                'subunit' => 'Cent',
                'subunit_to_unit' => '100',
                'symbol_first' => 'true',
                'html_entity' => '&#x0052;',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '710',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ZMK',
                'currency' => 'ZMK',
                'name' => 'Zambian Kwacha',
                'symbol' => 'ZK',
                'subunit' => 'Ngwee',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '894',
                'currency_rate' => 1
            ],
            [
                'priority' => '100',
                'iso_code' => 'ZMW',
                'currency' => 'ZMW',
                'name' => 'Zambian Kwacha',
                'symbol' => 'ZK',
                'subunit' => 'Ngwee',
                'subunit_to_unit' => '100',
                'symbol_first' => 'false',
                'html_entity' => '',
                'decimal_mark' => '.',
                'thousands_separator' => ',',
                'iso_numeric' => '967',
                'currency_rate' => 1
            ]
        ];
        DB::table('currencies')->insert($currencies);
    }
}
